name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          EC2_SSH_KEY: ${{ vars.EC2_SSH_KEY }}
          EC2_HOST: ${{ vars.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Copy project to EC2
        env:
          EC2_USER: ${{ vars.EC2_USER }}
          EC2_HOST: ${{ vars.EC2_HOST }}

        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST \
            "mkdir -p /home/ubuntu/shadowman41/groupe3"
            
          scp -i ~/.ssh/id_rsa -r ./ \
            $EC2_USER@$EC2_HOST:/home/ubuntu/${{ github.repository }}

      - name: Install dependencies and run app on EC2
        env:
          EC2_USER: ${{ vars.EC2_USER }}
          EC2_HOST: ${{ vars.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/${{ github.repository }}
            python3 -m venv venv
            venv/bin/pip install --upgrade pip
            venv/bin/pip install -r requirements.txt
            nohup venv/bin/python run.py > app.log 2>&1 &
          EOF
